#------------+
# INFO
#------------+
${color1}${font :size=14:bold}INFO ${hr 2}${font}
${voffset 5}${color1}OS :$alignr${color3}${execi 6000 lsb_release -d | grep 'Descr'|awk {'print $2 " " $3" " $4" " $5'}}
${voffset 2}${color1}Kernel :$alignr${color3} $kernel
${voffset 2}${color1}Uptime :$alignr${color3} $uptime
