${voffset 10}${color1}${font :size=14:bold}NETWORK ${hr 2}${font}

${color1}Up: ${color2}${upspeedf wlo1} KiB/s ${color1}Down: ${color2}${downspeedf wlo1} KiB/s
${color1}${upspeedgraph wlo1 22,155 -l} ${downspeedgraph wlo1 22,155 -l}

