#------------+
# PROCESSES
#------------+
${voffset 10}${color1}${font :size=14:bold}PROCESSES ${hr 2}${font}
${voffset 5}${color1}Name${goto 180}CPU%${alignr}MEM%
${color2}${top name 1} ${goto 180}${top cpu 1}${alignr}${top mem 1}${color3}
${top name 2} ${goto 180}${top cpu 2}${alignr}${top mem 2}
${top name 3} ${goto 180}${top cpu 3}${alignr}${top mem 3}
${top name 4} ${goto 180}${top cpu 4}${alignr}${top mem 4}
${top name 5} ${goto 180}${top cpu 5}${alignr}${top mem 5}
