#------------+
#TEMPS
#------------+
${voffset 10}${color1}${font :size=14:bold}TEMPS ${hr 2}${font}
${voffset 5}${color1}CPU : ${color3}${execi 5 sensors | grep Tdie: | cut -c 16-19}°C
${voffset 2}${color1}GPU : ${color3}${nvidia temp}°C
